version: '3'
services:
  meta-agent:
    build:
      context: .
      dockerfile: ./meta_agent/Dockerfile
    env_file: ./meta_agent/.env
    ports:
      - "5002:5000"
    volumes:
      - ./meta_agent:/app/meta_agent
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  web-ui:
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - meta-agent
    volumes:
      - ./web_ui:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
