version: '3'
services:
  meta-agent:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"

  web-ui:
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - meta-agent
