version: '3'
services:
  meta-agent:
    build:
      context: ./meta_agent
      dockerfile: Dockerfile
    env_file: ./meta_agent/.env
    ports:
      - "5002:5000"

  web-ui:
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - meta-agent
